### ISSUE TITLE
Add a contributor agreement?

### ISSUE THREAD

**Issue by danielcompton** [jaunt-lang/jaunt#25]
Not sure if this is necessary to follow Clojure's lead here?

**Comment by bbatsov** [comment]
I hope it's not. :-)

**Comment by arrdem** [comment]
No it isn't. The contributor agreement is required only so that in the future if appropriate Rich can re-license Clojure under another open source license. In the interests of simplicity and not having the book  keeping I'm content to say that Jaunt is EPL'd forever.
