### ISSUE TITLE
Add Clojars badge to README

### ISSUE THREAD

**Issue by arrdem** [jaunt-lang/jaunt#59]
Self explanatory. It'd be nice if there was a way to pin the latest stable release vs the latest snapshot.

**Comment by danielcompton** [comment]
See https://github.com/clojars/clojars-web/issues/398

**Comment by arrdem** [comment]
So I found a workaround for this. Use a tag badge for the release (releases are tagged `vA.B.C`) and use the clojars badge for the latest snapshot coordinates.
