### ISSUE TITLE
Add a jaunt reader conditional

### ISSUE THREAD

**Issue by danielcompton** [jaunt-lang/jaunt#68]
I'm not sure what the precise semantics should be here, but it could be good to add a Reader Conditional, say `#clojarr` which people can use to maintain libraries if Clojarr diverges from Clojure, and the package maintainers want to help both stay compatible.

**Comment by arrdem** [comment]
Probably gonna be `:jnt` ala `:clj` reader conditional expressions. Whether Jaunt takes `:clj` reader conditional expressions when there isn't a `:jnt` is up for debate. I think the answer is probably. Always evaluating `:clj` and evaluating `:jnt` if present just has too many traps.
