### ISSUE TITLE
Get a better name

### ISSUE THREAD

**Issue by arrdem** [jaunt-lang/jaunt#69]
The only consistent feedback from "release day" was that the name is :hankey:. Understandable and subject to change, but what to and why is a legitimate question.

**Comment by arrdem** [comment]
> Figure out what you want to accomplish, and choose an appropriate name.

**Comment by arrdem** [comment]
[Gram](https://en.wikipedia.org/wiki/Gram_%28mythology%29), appropriate because it's a reforged sword. Not especially googleable, but at least it doesn't name conflict with anything in the existing clj ecosystem.

**Comment by yurrriq** [comment]
Re: googleability. ["golang"](https://www.google.com/#q=golang) seems to work pretty well so I would imagine "gramlang" could be good too.

**Comment by arrdem** [comment]
Maybe. It's just a name and I've used worse before. I guess that "gram" just doesn't strike me as memorable at all. The other names I've used for stuff have been deliberately kinda rare or jokes so that they would stick. Gram is still a term in common usage, doesn't really fit that bill.

Maybe [gungnir](https://en.wikipedia.org/wiki/Gungnir) is better in that regard and it kinda plays to the "do the right thing" goal I have, but nobody's gonna remember how to spell that.

**Comment by arrdem** [comment]
From @weavejester on reddit:

> You could maybe have some play on "Clojure+more", like "Clomore" or "Claymore". Or perhaps "Clojump", "Clojolt", "Clojaunt" or something else that implies movement.

**Comment by turbopape** [comment]
Maybe cleejer, a play on the sound of clojure, clever, and clearer, while
still sounding like compiler and cheerer?
Le 23 févr. 2016 08:05, "Reid D McKenzie" notifications@github.com a
écrit :

**Comment by arrdem** [comment]
Unless there is particular objection, I'm leaning towards `jaunt`, package `me.arrdem/jaunt` until such time as it may become `org.jaunt-lang/jaunt` because there are other committers. While it's even worse off than claymore in terms of domain availability I think it captures the idea that I really don't know where this project is going, it is sort of a carefree jaunt.

**Comment by arrdem** [comment]
Jaunt it is.

**Comment by yurrriq** [comment]
:tada:

**Comment by turbopape** [comment]
+1
