### ISSUE TITLE
Share New Compiler Design Choices

### ISSUE THREAD

**Issue by turbopape** [jaunt-lang/jaunt#75]
I think the main departure from mainstream Clojure is the compiler choices made by @arrdem and academic or implementation work done so far in order to implement them. Maybe taking the time to share those (or even sharing pointers to presentation or academic papers) might whet the community's appetite and appeal for contributors?

**Comment by arrdem** [comment]
Changelog created and published. Blog posts/demos will be eventually forthcoming, but I'm tracking those elsewhere.
